memsched: RTAS2013 version
This version of memguard is used for RTAS2013 paper.
It support per-core and per-task memory bandwidth assignment with
reclaiming features.

It can only be loaded as a module after you compile the kernel with
CONFIG_SCHED_EVENT_THROTTLE=y enabled.

Once it is loaded, it provides several configuration interfaces as follows:

- per-core bandwidth assignment.

  assign 900,100,100,100 MB/s for Core 0,1,2,3
  # echo mb 900 100 100 100 > /sys/kernel/debug/memsched/limit

  assign 70%,10%,10%,10% of guaranteed bandwidth(r_min) for Core 0,1,2,3
  # echo 70 10 10 10 > /sys/kernel/debug/memsched/limit

- per-task mode (use task priority as core's memory weight)

  enable per-task mode
  # echo taskprio 1 > /sys/kernel/debug/memsched/control

  disble per-task mode (=per-core mode)
  # echo taskprio 0 > /sys/kernel/debug/memsched/control

- set maxbw (r_min in the paper)

  # echo maxbw 1200 > /sys/kernel/debug/memesched/control

- reclaim control

  enable
  # echo reclaim 1 > /sys/kernel/debug/memesched/control

  disable
  # echo reclaim 0 > /sys/kernel/debug/memesched/control

- exclusive mode control

  share b/w sharing mode in the paper
  # echo exclusive 2 > /sys/kernel/debug/memsched/control

  last exclusive. last core exclusively use the rest b/w (not in the paper)
  # echo exclusive 1 > /sys/kernel/debug/memsched/control

  no spare sharing mode
  # echo exclusive 0 > /sys/kernel/debug/memsched/control

- statistics

  reclaim statistics
  # cat /sys/kernel/debug/memsched/failcnt
throttled: 0 0 0 0	   # per-core throttled count
throttle_error: 0 0 0 0    # per-core reclaim underrun error count
core-pct   10    20    30    40    50    60    70    80    90    100
--------------------------------------------------------------------
   0        0     0     0     0     0     0     0     0     0     0
   1        0     0     0     0     0     0     0     0     0     0
   2        0     0     0     0     0     0     0     0     0     0
   3        0     0     0     0     0     0     0     0     0     0
exclusive: 0 0 0 0	   # per-core exclusive mode usage counts
total_periods 151	   # core0's total active periods - WARNING:
			   #   not counted when core0 is inactive(no runnable task)